

row_data = {
"robot_id": "VW371 Standard",
"program_id": "FOLGE056",
"Program File Name": "FOLGE056",
"Program Name": "FOLGE056",
"OWNER": "Inpro",
"COMMENT": "VW371 Jetta",
"PROG_SIZE": "",
"CREATE": "",
"MODIFIED": "",
"FILE_NAME": "FOLGE056",
"VERSION": "",
"LINE_COUNT": "",
"MEMORY_SIZE": "",
"PROTECT": "",
"STORAGE": "",
"STACK_SIZE": "",
"TASK_PRIORITY": "",
"TIME_SLICE": "",
"BUSY_LAMP_OFF": "",
"ABORT_REQUEST": "",
"PAUSE_REQUEST": "",
"DEFAULT_GROUP": "",
"CONTROL_CODE": "",
}

row_data = {
"robot_id": "VW371 Standard",
"program_id": "FOLGE058",
"Program File Name": "FOLGE058",
"Program Name": "FOLGE058",
"OWNER": "Inpro",
"COMMENT": "VW371 Take In",
"PROG_SIZE": "",
"CREATE": "",
"MODIFIED": "",
"FILE_NAME": "FOLGE058",
"VERSION": "",
"LINE_COUNT": "",
"MEMORY_SIZE": "",
"PROTECT": "",
"STORAGE": "",
"STACK_SIZE": "",
"TASK_PRIORITY": "",
"TIME_SLICE": "",
"BUSY_LAMP_OFF": "",
"ABORT_REQUEST": "",
"PAUSE_REQUEST": "",
"DEFAULT_GROUP": "",
"CONTROL_CODE": "",
}